### ISSUE TITLE
Ask for pretrained weights files

### ISSUE THREAD

**Issue by heatingma** [naver/bq-nco#3]
Hello, may I ask if you can provide pretrained weights files of TSP100, TSP500 and TSP1000

**Comment by ddrakulic** [comment]
Hello,

We do not have separate models for larger problem sizes. We train all models on 100-node instances and apply them to problems with 100, 200, 500, and 1000 nodes. So, you should use tsp.best for all problem sizes.

If you have issues with reproducing the results from the paper, add --knns 250 during inference to improve runtime efficiency and performance.

**Comment by heatingma** [comment]
Thank you for your answer. I have discovered my mistake.
